/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry { 'nickname' : string, 'score' : bigint }
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeNickname' : ActorMethod<[string], undefined>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'getCallerNickname' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'authorNickname' : string,
        'text' : string,
        'timestamp' : Time,
        'reactions' : Array<[string, bigint]>,
      }
    >
  >,
  'getLastWeeklyReset' : ActorMethod<[], [] | [Time]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTopScores' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getWeeklyTopScores' : ActorMethod<[], Array<LeaderboardEntry>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moderatorDeleteMessage' : ActorMethod<[bigint, string], undefined>,
  'postChatMessage' : ActorMethod<[string], undefined>,
  'removeReaction' : ActorMethod<[bigint, string], undefined>,
  'resetWeeklyScores' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNickname' : ActorMethod<[string], undefined>,
  'submitScore' : ActorMethod<[bigint], undefined>,
  'submitWeeklyScore' : ActorMethod<[bigint], undefined>,
  'validateNickname' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];